# Generated by Django 2.1.3 on 2018-11-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('apellidoPaterno', models.CharField(max_length=70)),
                ('apellidoMaterno', models.CharField(max_length=70)),
                ('Sexo',models.CharField(max_length = 20)),
                ('nombres', models.CharField(max_length=70)),
            ],
        ),
    ]
